# Site settings
title: ğ’¦ğ’¾ğ“ğ“ğ’¶ğ’½
description: ğ’¦ğ’¾ğ“ğ“ğ’¶ğ’½
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Smile Killah
user_description: ä¸ªäººä¸»ä¹‰æå¼ºçš„çŠ¯2å„¿ç«¥ä¸€å !
#user_description: è¿™çŸ­çŸ­çš„ä¸€ç”Ÿï¼Œæˆ‘ä»¬æœ€ç»ˆéƒ½ä¼šå¤±å»ã€‚ä½ ä¸å¦¨å¤§èƒ†ä¸€äº›ï¼Œçˆ±ä¸€ä¸ªäººï¼Œæ”€ä¸€åº§å±±ï¼Œè¿½ä¸€ä¸ªæ¢¦ã€‚
user_title: Helloï¼ŒStranger !



